version: '3'
services:
  ansible:
    container_name: ansible
    build: docker/ansible
    tty: true
    working_dir: /work
    volumes:
      - .:/work/.

  target01:
    container_name: server01
    build: docker/server
    tty: true
