- hosts: all
  tasks:
    - name: install epel-release
      yum:
        name: epel-release
        state: present

    - name: install nginx
      yum:
        name: nginx
        state: present

    - name: update nginx
      yum:
        name: nginx
        state: latest
      when: ( nginx.update | default(false) | bool )
